#ifndef ROMAJI_IME_H
#define ROMAJI_IME_H

#pragma once

/* GENERATED by cbindgen. Do not edit by hand. Regenerate: cargo run -p xtask -- gen-header */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/*
 The IME consumed the key; the host app must not also handle it.
 */
#define RIME_CONSUMED 1

/*
 The preedit (composition) string changed.
 */
#define RIME_PREEDIT 2

/*
 The candidate list changed.
 */
#define RIME_CANDIDATES 4

/*
 There is committed text to fetch and insert.
 */
#define RIME_COMMIT 8

/*
 Opaque process-global engine handle.
 */
typedef struct RimeEngine RimeEngine;

/*
 Opaque per-input-context session handle.

 The C-string caches keep returned `const char*` pointers valid until the next
 mutating call (`process_key` / `select_candidate` / `reset`).
 */
typedef struct RimeSession RimeSession;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Create an engine. `config_dir`/`user_data_dir` may be NULL. The returned
 pointer must be freed with [`rime_engine_free`].
 */
struct RimeEngine *rime_engine_new(const char *config_dir, const char *user_data_dir);

/*
 Free an engine created by [`rime_engine_new`]. NULL is ignored.
 */
void rime_engine_free(struct RimeEngine *engine);

/*
 Whether a cloud-AI converter is configured (config.json / env loaded). Useful
 for diagnostics and for deciding whether to offer AI conversion.
 */
bool rime_engine_has_ai(const struct RimeEngine *engine);

/*
 Whether the frontend should auto-convert after a typing pause (config).
 */
bool rime_auto_convert_enabled(const struct RimeEngine *engine);

/*
 Idle delay in milliseconds before auto-converting (config).
 */
uint32_t rime_auto_convert_delay_ms(const struct RimeEngine *engine);

/*
 Start a new input session. Returns NULL if `engine` is NULL. Free with
 [`rime_session_free`]. The engine must outlive all its sessions.
 */
struct RimeSession *rime_session_new(struct RimeEngine *engine);

/*
 Free a session created by [`rime_session_new`]. NULL is ignored.
 */
void rime_session_free(struct RimeSession *session);

/*
 Clear all composition state for the session.
 */
void rime_session_reset(struct RimeSession *session);

/*
 Feed one platform-neutral key event. Returns a `RimeResultFlags` bitmask
 (see the engine's `flags` module): CONSUMED=1, PREEDIT=2, CANDIDATES=4,
 COMMIT=8. Returns 0 if `session` is NULL.
 */
uint32_t rime_process_key(struct RimeSession *session, uint32_t keysym, uint32_t mods);

/*
 The current preedit (composition) string. Valid until the next mutating call.
 */
const char *rime_get_preedit(const struct RimeSession *session);

/*
 Number of conversion candidates.
 */
size_t rime_get_candidate_count(const struct RimeSession *session);

/*
 The candidate string at `index`, or NULL if out of range. Valid until the
 next mutating call.
 */
const char *rime_get_candidate_text(const struct RimeSession *session, size_t index);

/*
 Index of the highlighted candidate.
 */
size_t rime_get_highlighted_index(const struct RimeSession *session);

/*
 Commit the candidate at `index`. Returns a result-flags bitmask.
 */
uint32_t rime_select_candidate(struct RimeSession *session, size_t index);

/*
 Text to commit after a key event set the COMMIT flag. Valid until the next
 mutating call; empty string if nothing to commit.
 */
const char *rime_get_commit_text(const struct RimeSession *session);

/*
 Begin an asynchronous cloud-AI conversion of the current input, passing the
 surrounding document text as context. Returns a request id to poll, or 0 if
 AI conversion is unavailable (no converter configured, nothing composing, or
 candidates already showing). The conversion runs on an internal background
 thread; call [`rime_poll_ai_result`] on the SAME thread as other session
 calls until it resolves.
 */
uint64_t rime_begin_ai_convert(struct RimeSession *session,
                               const char *context_before,
                               const char *context_after);

/*
 Poll a conversion started by [`rime_begin_ai_convert`].
 Returns: 0 = pending, 1 = ready/final (candidates/preedit updated), 2 =
 streaming (partial candidates updated, keep polling), -1 = error/unavailable
 (the frontend should fall back to the local converter).
 */
int32_t rime_poll_ai_result(struct RimeSession *session, uint64_t req_id);

/*
 The most recent AI conversion error message (empty if none). Valid until the
 next poll. For diagnostics / user-facing error display.
 */
const char *rime_get_last_error(const struct RimeSession *session);

/*
 The C ABI version. Frontends should check this matches what they were built
 against.
 */
uint32_t rime_abi_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ROMAJI_IME_H */
